# Generated by Django 5.0.2 on 2024-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='club',
        ),
    ]
